#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 13 15:46:24 2020

@author: rzohreh
"""


import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
plt.scatter(W1[:,0], W1[:,1], marker='o');


y = list(W1[:,0])
z = list(W1[:,1])
n = list(range(0,33))

fig, ax = plt.subplots()
ax.scatter(z, y)

for i, txt in enumerate(n):
    ax.annotate(txt, (z[i], y[i]))
    ax.annotate(txt, (z,y))